# This is the definitive build configuration for a nested Next.js project.
# This file MUST be in the root of your GitHub repository.

[build]
  # This tells Netlify where your Next.js project is located.
  base = "invictus-nextjs"

  # The command to build the site, run from within the 'base' directory.
  command = "npm run build"

  # The directory containing the build output, relative to the 'base' directory.
  publish = ".next"

# This plugin is essential for running the Next.js server runtime.
[[plugins]]
  package = "@netlify/plugin-nextjs"